import React, { useState, useEffect, useMemo } from 'react';
import {
  PatientContext,
  VitalSignsData,
  GCSData,
  InterventionData,
  CannedTemplate,
  SavedRecord,
  ShiftType,
} from './types';
import { DEFAULT_TEMPLATES } from './data/defaultTemplates';
import { replaceTemplateVariables } from './utils/templateReplacer';
import { PatientContextForm } from './components/PatientContextForm';
import { VitalSignsForm } from './components/VitalSignsForm';
import { GCSForm } from './components/GCSForm';
import { TemplateSelector } from './components/TemplateSelector';
import { RecordPreview } from './components/RecordPreview';
import { SavedRecordsDrawer } from './components/SavedRecordsDrawer';
import { ClinicalReferenceModal } from './components/ClinicalReferenceModal';
import {
  ClipboardList,
  BookOpen,
  History,
  Sparkles,
  RotateCcw,
  ShieldCheck,
  Hospital,
} from 'lucide-react';

const STORAGE_KEY_RECORDS = 'nursing_app_saved_records';
const STORAGE_KEY_TEMPLATES = 'nursing_app_custom_templates';

export default function App() {
  // Current Date & Time initialization
  const getInitialContext = (): PatientContext => {
    const now = new Date();
    const hours = now.getHours();
    let defaultShift: ShiftType = 'day';
    if (hours >= 16 && hours < 24) defaultShift = 'evening';
    else if (hours < 8) defaultShift = 'night';

    return {
      bedNumber: '12-1',
      recordDate: now.toISOString().split('T')[0],
      recordTime: `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`,
      shift: defaultShift,
      chiefComplaint: '無特殊主訴',
    };
  };

  const [context, setContext] = useState<PatientContext>(getInitialContext);

  const [vitalSigns, setVitalSigns] = useState<VitalSignsData>({
    bt: '36.8',
    hr: '76',
    rr: '18',
    sbp: '120',
    dbp: '78',
    spo2: '98',
    o2Device: 'Room Air',
    o2Flow: '',
    painScore: '0',
    painLocation: '手術傷口',
    painNature: '悶痛',
    bloodSugar: '',
  });

  const [gcs, setGcs] = useState<GCSData>({
    eye: 4,
    verbal: 5,
    motor: 6,
    leftPupilSize: '2.5',
    rightPupilSize: '2.5',
    leftPupilReflex: '+',
    rightPupilReflex: '+',
  });

  const [intervention, setIntervention] = useState<InterventionData>({
    focusCategory: '常規病況穩定',
    actionDetail: '予常規病房巡房，維持病室安全，床欄拉起固定，呼叫鈴置於身旁，衛教下床防跌',
    responseDetail: '病人精神可，情緒平穩，表示清楚防跌注意事項',
    followUpTime: '每班巡房',
    followUpBT: '36.8',
    followUpPain: '0',
    followUpSpO2: '98',
    followUpRR: '18',
    customNotes: '',
    drainTubeName: 'JP引流管',
    drainAmount: '25',
    drainColor: '淡血水色',
    woundLocation: '腹部傷口',
  });

  // Templates State
  const [templates, setTemplates] = useState<CannedTemplate[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_TEMPLATES);
      if (saved) {
        const parsed = JSON.parse(saved);
        if (Array.isArray(parsed) && parsed.length > 0) return parsed;
      }
    } catch (e) {
      console.error(e);
    }
    return DEFAULT_TEMPLATES;
  });

  const [selectedTemplate, setSelectedTemplate] = useState<CannedTemplate>(DEFAULT_TEMPLATES[0]);

  // Saved Records History State
  const [savedRecords, setSavedRecords] = useState<SavedRecord[]>(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEY_RECORDS);
      if (saved) {
        return JSON.parse(saved);
      }
    } catch (e) {
      console.error(e);
    }
    return [];
  });

  // Generated Text State & Manual Override
  const [manualText, setManualText] = useState<string | null>(null);
  const [isReferenceModalOpen, setIsReferenceModalOpen] = useState(false);

  // Compute Auto Generated Text
  const autoGeneratedText = useMemo(() => {
    return replaceTemplateVariables(selectedTemplate.templateText, context, vitalSigns, gcs, intervention);
  }, [selectedTemplate, context, vitalSigns, gcs, intervention]);

  const displayedText = manualText !== null ? manualText : autoGeneratedText;

  // Persist templates to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY_TEMPLATES, JSON.stringify(templates));
    } catch (e) {
      console.error(e);
    }
  }, [templates]);

  // Persist records to localStorage
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY_RECORDS, JSON.stringify(savedRecords));
    } catch (e) {
      console.error(e);
    }
  }, [savedRecords]);

  // Handle template selection
  const handleSelectTemplate = (tmpl: CannedTemplate) => {
    setSelectedTemplate(tmpl);
    setManualText(null); // reset manual override when user changes template
  };

  // Custom template save / delete
  const handleSaveCustomTemplate = (newTmpl: CannedTemplate) => {
    const existingIndex = templates.findIndex((t) => t.id === newTmpl.id);
    let updated: CannedTemplate[];
    if (existingIndex >= 0) {
      updated = [...templates];
      updated[existingIndex] = newTmpl;
    } else {
      updated = [newTmpl, ...templates];
    }
    setTemplates(updated);
    setSelectedTemplate(newTmpl);
    setManualText(null);
  };

  const handleDeleteCustomTemplate = (id: string) => {
    const updated = templates.filter((t) => t.id !== id);
    setTemplates(updated);
    if (selectedTemplate.id === id) {
      setSelectedTemplate(DEFAULT_TEMPLATES[0]);
      setManualText(null);
    }
  };

  const handleResetDefaults = () => {
    const customOnes = templates.filter((t) => !t.isDefault);
    const refreshed = [...customOnes, ...DEFAULT_TEMPLATES];
    setTemplates(refreshed);
    setSelectedTemplate(DEFAULT_TEMPLATES[0]);
    setManualText(null);
  };

  // Handle save record
  const handleSaveRecord = (recData: Omit<SavedRecord, 'id' | 'createdAt'>) => {
    const newRecord: SavedRecord = {
      ...recData,
      id: 'rec-' + Date.now(),
      createdAt: new Date().toISOString(),
    };
    setSavedRecords([newRecord, ...savedRecords]);
  };

  // Handle load record into editor
  const handleLoadRecord = (record: SavedRecord) => {
    setContext((prev) => ({
      ...prev,
      bedNumber: record.bedNumber,
      recordDate: record.date,
      recordTime: record.time,
      shift: record.shift,
    }));
    setManualText(record.content);
    // Smooth scroll to preview panel on mobile
    const el = document.getElementById('record-preview-panel');
    if (el) {
      el.scrollIntoView({ behavior: 'smooth' });
    }
  };

  const handleDeleteRecord = (id: string) => {
    setSavedRecords(savedRecords.filter((r) => r.id !== id));
  };

  const handleClearAllRecords = () => {
    setSavedRecords([]);
  };

  // Quick Clinical Case Scenarios (Demo fills)
  const applyClinicalCase = (type: 'fever' | 'pain' | 'dyspnea' | 'routine') => {
    setManualText(null);
    if (type === 'fever') {
      const tmpl = templates.find((t) => t.id === 'dart-fever') || templates[0];
      setSelectedTemplate(tmpl);
      setVitalSigns({
        bt: '38.8',
        hr: '104',
        rr: '22',
        sbp: '130',
        dbp: '82',
        spo2: '97',
        o2Device: 'Room Air',
        o2Flow: '',
        painScore: '0',
        painLocation: '',
        painNature: '',
        bloodSugar: '',
      });
      setIntervention((prev) => ({
        ...prev,
        actionDetail: '依醫囑給予 Acetaminophen 500mg 1# PO，提供冰枕使用，鼓勵多喝溫開水與保暖',
        followUpTime: '1小時後',
        followUpBT: '37.1',
      }));
    } else if (type === 'pain') {
      const tmpl = templates.find((t) => t.id === 'dart-pain') || templates[0];
      setSelectedTemplate(tmpl);
      setVitalSigns({
        bt: '36.8',
        hr: '88',
        rr: '20',
        sbp: '138',
        dbp: '86',
        spo2: '98',
        o2Device: 'Room Air',
        o2Flow: '',
        painScore: '6',
        painLocation: '腹部手術傷口',
        painNature: '牽扯刺痛',
        bloodSugar: '',
      });
      setIntervention((prev) => ({
        ...prev,
        actionDetail: '依醫囑給予 Ultracet 1# PO，協助抬高床頭與膝部墊枕採舒適臥位，指導深呼吸放鬆',
        followUpTime: '45分鐘後',
        followUpPain: '2',
      }));
    } else if (type === 'dyspnea') {
      const tmpl = templates.find((t) => t.id === 'dart-dyspnea') || templates[0];
      setSelectedTemplate(tmpl);
      setVitalSigns({
        bt: '37.0',
        hr: '112',
        rr: '26',
        sbp: '144',
        dbp: '90',
        spo2: '90',
        o2Device: 'Nasal Cannula',
        o2Flow: '3',
        painScore: '0',
        painLocation: '',
        painNature: '',
        bloodSugar: '',
      });
      setIntervention((prev) => ({
        ...prev,
        actionDetail: '立即協助床頭抬高 60 度採半坐臥姿，給予 Nasal cannula 3 L/min 使用，並即刻通知值班醫師到場評估',
        followUpTime: '30分鐘後',
        followUpSpO2: '98',
        followUpRR: '18',
      }));
    } else {
      const tmpl = templates.find((t) => t.id === 'dart-routine') || templates[0];
      setSelectedTemplate(tmpl);
      setVitalSigns({
        bt: '36.7',
        hr: '74',
        rr: '18',
        sbp: '118',
        dbp: '76',
        spo2: '98',
        o2Device: 'Room Air',
        o2Flow: '',
        painScore: '0',
        painLocation: '',
        painNature: '',
        bloodSugar: '',
      });
      setGcs({
        eye: 4,
        verbal: 5,
        motor: 6,
        leftPupilSize: '2.5',
        rightPupilSize: '2.5',
        leftPupilReflex: '+',
        rightPupilReflex: '+',
      });
      setIntervention((prev) => ({
        ...prev,
        actionDetail: '予常規病房巡房，維持病室安全，床欄拉起固定，呼叫鈴置於身旁，衛教下床防跌',
      }));
    }
  };

  return (
    <div className="min-h-screen bg-slate-100/90 text-slate-800 flex flex-col font-sans selection:bg-teal-100 selection:text-teal-900">
      {/* Top Application Header */}
      <header className="bg-white border-b border-slate-200 sticky top-0 z-30 shadow-xs">
        <div className="max-w-7xl mx-auto px-4 py-3 sm:px-6 flex flex-wrap items-center justify-between gap-3">
          <div className="flex items-center gap-2.5">
            <div className="w-10 h-10 rounded-xl bg-teal-600 flex items-center justify-center text-white shadow-xs">
              <ClipboardList className="w-5 h-5" />
            </div>
            <div>
              <div className="flex items-center gap-2">
                <h1 className="text-lg sm:text-xl font-bold text-slate-900 tracking-tight">
                  護理記錄快打產生器
                </h1>
                <span className="text-[11px] font-semibold px-2 py-0.5 rounded-full bg-teal-50 text-teal-700 border border-teal-200 hidden sm:inline-flex items-center gap-1">
                  <ShieldCheck className="w-3 h-3" />
                  臨床護理即時代入
                </span>
              </div>
              <p className="text-xs text-slate-600 hidden sm:block">
                輸入時間日期、生命徵象、GCS昏迷指數，自動套入焦點罐頭片語，一鍵複製貼入HIS病歷系統
              </p>
            </div>
          </div>

          {/* Header Action Buttons */}
          <div className="flex items-center gap-2">
            {/* Quick Case Populators */}
            <div className="hidden lg:flex items-center gap-1 bg-slate-50 p-1 rounded-lg border border-slate-200 text-xs">
              <span className="text-[11px] text-slate-600 font-medium px-1.5 flex items-center gap-1">
                <Sparkles className="w-3 h-3 text-amber-500" />
                臨床案例快捷:
              </span>
              <button
                type="button"
                onClick={() => applyClinicalCase('routine')}
                className="px-2 py-0.5 rounded text-[11px] font-medium hover:bg-white hover:shadow-xs transition-colors cursor-pointer text-slate-700"
              >
                常規巡房
              </button>
              <button
                type="button"
                onClick={() => applyClinicalCase('fever')}
                className="px-2 py-0.5 rounded text-[11px] font-medium hover:bg-white hover:shadow-xs transition-colors cursor-pointer text-amber-700"
              >
                發燒處置
              </button>
              <button
                type="button"
                onClick={() => applyClinicalCase('pain')}
                className="px-2 py-0.5 rounded text-[11px] font-medium hover:bg-white hover:shadow-xs transition-colors cursor-pointer text-rose-700"
              >
                止痛評估
              </button>
              <button
                type="button"
                onClick={() => applyClinicalCase('dyspnea')}
                className="px-2 py-0.5 rounded text-[11px] font-medium hover:bg-white hover:shadow-xs transition-colors cursor-pointer text-sky-700"
              >
                呼吸喘給氧
              </button>
            </div>

            {/* Reference Guide Button */}
            <button
              type="button"
              id="open-reference-modal-button"
              onClick={() => setIsReferenceModalOpen(true)}
              className="px-2.5 py-1.5 rounded-lg bg-slate-50 hover:bg-slate-100 text-slate-700 border border-slate-200 text-xs font-medium flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <BookOpen className="w-3.5 h-3.5 text-teal-600" />
              <span>臨床速查表</span>
            </button>

            {/* Jump to Saved Records */}
            <button
              type="button"
              onClick={() => {
                const el = document.getElementById('saved-records-panel');
                if (el) el.scrollIntoView({ behavior: 'smooth' });
              }}
              className="px-2.5 py-1.5 rounded-lg bg-emerald-50 hover:bg-emerald-100 text-emerald-800 border border-emerald-200 text-xs font-semibold flex items-center gap-1.5 transition-colors cursor-pointer"
            >
              <History className="w-3.5 h-3.5 text-emerald-600" />
              <span>本機已存 ({savedRecords.length})</span>
            </button>
          </div>
        </div>
      </header>

      {/* Main App Body */}
      <main className="max-w-7xl mx-auto px-4 py-4 sm:px-6 w-full grow">
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-5 items-start">
          {/* Left Column: Data Input Modules (Context, Vital Signs, GCS, Template Selector) */}
          <div className="lg:col-span-7 space-y-4">
            {/* 1. Date, Time, Shift, Bed & Intervention */}
            <PatientContextForm
              context={context}
              intervention={intervention}
              onContextChange={setContext}
              onInterventionChange={setIntervention}
            />

            {/* 2. Vital Signs & Pain & Blood Sugar */}
            <VitalSignsForm vitalSigns={vitalSigns} onChange={setVitalSigns} />

            {/* 3. GCS Neurological Score & Pupils */}
            <GCSForm gcs={gcs} onChange={setGcs} />

            {/* 4. Canned Template Selector & Customizer */}
            <TemplateSelector
              templates={templates}
              selectedTemplateId={selectedTemplate.id}
              onSelectTemplate={handleSelectTemplate}
              onSaveCustomTemplate={handleSaveCustomTemplate}
              onDeleteCustomTemplate={handleDeleteCustomTemplate}
              onResetDefaults={handleResetDefaults}
            />
          </div>

          {/* Right Column: Live Generated Record & Local History Scratchpad */}
          <div className="lg:col-span-5 space-y-4 lg:sticky lg:top-20">
            {/* Live Generated Record Output Card */}
            <RecordPreview
              generatedText={displayedText}
              onTextChange={(newTxt) => setManualText(newTxt)}
              currentTemplate={selectedTemplate}
              context={context}
              vitalSigns={vitalSigns}
              onSaveRecord={handleSaveRecord}
              onResetRecord={() => setManualText(null)}
            />

            {/* Local Saved Records Drawer */}
            <SavedRecordsDrawer
              records={savedRecords}
              onLoadRecord={handleLoadRecord}
              onDeleteRecord={handleDeleteRecord}
              onClearAll={handleClearAllRecords}
            />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="bg-white border-t border-slate-200 py-3 mt-6 text-center text-xs text-slate-600">
        <div className="max-w-7xl mx-auto px-4 flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center gap-1.5">
            <Hospital className="w-3.5 h-3.5 text-teal-600" />
            <span className="font-semibold text-slate-700">護理記錄快打產生器</span>
            <span>- 臨床輔助工具，專供病房、ICU、門急診快速書寫代入</span>
          </div>
          <div className="text-slate-600">
            提示：本工具所有記錄均存放於您的本機瀏覽器內，無外傳雲端，保障病人隱私安全。
          </div>
        </div>
      </footer>

      {/* Clinical Reference Handbook Modal */}
      <ClinicalReferenceModal
        isOpen={isReferenceModalOpen}
        onClose={() => setIsReferenceModalOpen(false)}
      />
    </div>
  );
}
